### ISSUE TITLE
RFE: remove `Include in net worth` option for credit card account

### ISSUE THREAD

**Issue by myakove** [itairaz1/israeli-bank-firefly-importer#32]
When create a credit card account via the importer, there should be an option to create it without `Include in net worth`
Most credit card already calculates in the main bank account, so there is no need to do it again.

For example:
my main account is `hapohlim` which already include the expense from my credit card (this is the bank that the card associate to)

**Comment by itairaz1** [comment]
So you see all transactions of your credit cards in Hapoalim account (at firefly)?
What is `Include in net wort` option? is it something in the scrapper?

**Comment by myakove** [comment]
It's a setting in firefly for account.
I' thinking maybe when you create the account for the credit card add an option to create the account with this setting disable/enabled (can be setting inside your YAML config file for each credit card account)

If it's not possible, please free to close this issue and maybe just add this to your README.

**Comment by itairaz1** [comment]
OK, understood. Thank you for your feedback.
Since there are many options, the creation of the accounts are set with minimal settings, so you can change the settings as you wish right after, and it is promised that those settings wouldn't override later.
What do you think?
I will add this to the README.

**Comment by myakove** [comment]
Add to the README is perfect, thanks.
